from typing import Protocol

from porter.models import Product, ScrapedData, WatchList


class HtmlFetcher(Protocol):
    def fetch(self, url: str) -> str: ...


class ProductScraper(Protocol):
    def scrape(self, html: str) -> ScrapedData: ...


class ProductRepository(Protocol):
    def add_product(self, scraped: ScrapedData, url: str, list_id: int | None = None) -> Product: ...

    def list_products(self, list_id: int | None = None) -> list[Product]: ...

    def update_price(self, product_id: int, new_price: float) -> None: ...

    def remove_product(self, product_id: int) -> None: ...


class WatchListRepository(Protocol):
    def create_list(self, name: str) -> WatchList: ...

    def list_all_lists(self) -> list[WatchList]: ...

    def delete_list(self, list_id: int) -> None: ...

    def move_product_to_list(self, product_id: int, list_id: int) -> None: ...
